// Generated by github.com/kr/genbolt. DO NOT EDIT.
// See testdata/binmap.in.go.

package db

import encoding "encoding"
import binary "encoding/binary"
import bolt "github.com/coreos/bbolt"
import sample "github.com/kr/genbolt/testdata/sample"

const _ = binary.MaxVarintLen16
const _ = bolt.MaxKeySize

type T struct {
	db *bolt.Bucket
}

func (o *T) Bucket() *bolt.Bucket {
	return o.db
}

func (o *T) B() *SampleBinaryMap {
	return &SampleBinaryMap{bucket(o.db, keyB)}
}

type SampleBinaryMap struct {
	db *bolt.Bucket
}

func (o *SampleBinaryMap) Bucket() *bolt.Bucket {
	return o.db
}

func (o *SampleBinaryMap) Get(key []byte) *sample.Binary {
	rec := get(o.db, key)
	v := new(sample.Binary)
	if rec == nil {
		return v
	}
	err := encoding.BinaryUnmarshaler(v).UnmarshalBinary(rec)
	if err != nil {
		panic(err)
	}
	return v
}

func (o *SampleBinaryMap) GetByString(key string) *sample.Binary {
	return o.Get([]byte(key))
}

func (o *SampleBinaryMap) Put(key []byte, v *sample.Binary) {
	rec, err := encoding.BinaryMarshaler(v).MarshalBinary()
	if err != nil {
		panic(err)
	}
	put(o.db, key, rec)
}

func (o *SampleBinaryMap) PutByString(key string, v *sample.Binary) {
	o.Put([]byte(key), v)
}

var (
	keyB = []byte("B")
)

type db interface {
	Writable() bool
	CreateBucketIfNotExists([]byte) (*bolt.Bucket, error)
	Bucket([]byte) *bolt.Bucket
}

func bucket(db db, key []byte) *bolt.Bucket {
	if !db.Writable() {
		return db.Bucket(key)
	}
	b, err := db.CreateBucketIfNotExists(key)
	if err != nil {
		panic(err)
	}
	return b
}

func get(b *bolt.Bucket, key []byte) []byte {
	if b == nil {
		return nil
	}
	return b.Get(key)
}

func put(b *bolt.Bucket, key, value []byte) {
	err := b.Put(key, value)
	if err != nil {
		panic(err)
	}
}
