// Generated by github.com/kr/genbolt. DO NOT EDIT.
// See testdata/bytes.in.go

package db

import binary "encoding/binary"
import bolt "github.com/coreos/bbolt"

const _ = binary.MaxVarintLen16
const _ = bolt.MaxKeySize

// T is a nice thing.
type T struct {
	db *bolt.Bucket
}

func (o *T) Bucket() *bolt.Bucket {
	return o.db
}

// B is a byte slice.
// It is useful.
func (o *T) B() []byte {
	v := o.db.Get(keyB)
	c := make([]byte, len(v))
	copy(c, v)
	return c
}

// PutB stores x as the value of B.
//
// B is a byte slice.
// It is useful.
func (o *T) PutB(x []byte) {
	v := x
	put(o.db, keyB, v)
}

var (
	keyB = []byte("B")
)

func put(b *bolt.Bucket, key, value []byte) {
	err := b.Put(key, value)
	if err != nil {
		panic(err)
	}
}
