// Generated by github.com/kr/genbolt. DO NOT EDIT.
// See testdata/bytes.in.go.

package db

import binary "encoding/binary"
import bolt "github.com/coreos/bbolt"

const _ = binary.MaxVarintLen16
const _ = bolt.MaxKeySize

// T is a nice thing.
type T struct {
	db *bolt.Bucket
}

func (o *T) Bucket() *bolt.Bucket {
	return o.db
}

// B is a byte slice.
// It is useful.
func (o *T) B() []byte {
	rec := get(o.db, keyB)
	v := make([]byte, len(rec))
	copy(v, rec)
	return v
}

// PutB stores v as the value of B.
//
// B is a byte slice.
// It is useful.
func (o *T) PutB(v []byte) {
	rec := v
	put(o.db, keyB, rec)
}

var (
	keyB = []byte("B")
)

func get(b *bolt.Bucket, key []byte) []byte {
	if b == nil {
		return nil
	}
	return b.Get(key)
}

func put(b *bolt.Bucket, key, value []byte) {
	err := b.Put(key, value)
	if err != nil {
		panic(err)
	}
}
