// Generated by github.com/kr/genbolt. DO NOT EDIT.
// See testdata/json.in.go

package db

import json "encoding/json"
import sample "github.com/kr/genbolt/testdata/sample"

import binary "encoding/binary"
import bolt "github.com/coreos/bbolt"

const _ = binary.MaxVarintLen16
const _ = bolt.MaxKeySize

type T struct {
	db *bolt.Bucket
}

func (o *T) Bucket() *bolt.Bucket {
	return o.db
}

func (o *T) J() *sample.JSON {
	v := o.db.Get(keyJ)
	var x json.Unmarshaler = new(sample.JSON)
	err := json.Unmarshal(v, x)
	if err != nil {
		panic(err)
	}
	return x
}

// PutJ stores x as the value of J.
func (o *T) PutJ(x *sample.JSON) {
	v, err := json.Marshal(json.Marshaler(x))
	if err != nil {
		panic(err)
	}
	put(o.db, keyJ, v)
}

var (
	keyJ = []byte("J")
)

func put(b *bolt.Bucket, key, value []byte) {
	err := b.Put(key, value)
	if err != nil {
		panic(err)
	}
}
