// Generated by github.com/kr/genbolt. DO NOT EDIT.
// See testdata/userpkgrename.in.go.

package db

import binary "encoding/binary"
import json "encoding/json"
import bolt "github.com/coreos/bbolt"
import foo "github.com/kr/genbolt/testdata/sample"

const _ = binary.MaxVarintLen16
const _ = bolt.MaxKeySize

type T struct {
	db *bolt.Bucket
}

func (o *T) Bucket() *bolt.Bucket {
	return o.db
}

func (o *T) J() *foo.JSON {
	rec := get(o.db, keyJ)
	v := new(foo.JSON)
	if rec == nil {
		return v
	}
	err := json.Unmarshal(rec, json.Unmarshaler(v))
	if err != nil {
		panic(err)
	}
	return v
}

// PutJ stores v as the value of J.
func (o *T) PutJ(v *foo.JSON) {
	rec, err := json.Marshal(json.Marshaler(v))
	if err != nil {
		panic(err)
	}
	put(o.db, keyJ, rec)
}

var (
	keyJ = []byte("J")
)

func get(b *bolt.Bucket, key []byte) []byte {
	if b == nil {
		return nil
	}
	return b.Get(key)
}

func put(b *bolt.Bucket, key, value []byte) {
	err := b.Put(key, value)
	if err != nil {
		panic(err)
	}
}
